### PR TITLE
Remove theme and updated instructions

### PR DESCRIPTION
**Pull request by dmartine**
Hide custom theme from main page as I need to fix it for 1.2 release. Updated some instructions for install and code syntax

### CODE REVIEW

**Comment by andygup** [comment]
Looks like there are some conflicts. If you click the "Use the command line" link above it gives some hints on how to resolve them.

**Comment by jgravois** [comment]
this is because the branch you are proposing to merge is substantially behind Esri/`master` (108 [`commits`](https://github.com/dmartine/geodev-hackerlabs/tree/config-updates) compared to 123 [`commits`](https://github.com/Esri/geodev-hackerlabs/tree/master)).

you need to `pull` from upstream and resolve any conflicts before we'll be able to get this in.  i can help if you get stuck.

``` bash
git checkout config-updates
git pull upstream gh-pages
>> this is where you might have to resolve conflicts and commit
git push origin config-updates
```

**Comment by dmartine** [comment]
deleted branch will recreate a new branch

**Comment by jgravois** [comment]
the nuclear option works too.

**Pull request closed without merging**
