### PR TITLE
bump to jsapi 4.1, leaflet 1.0.0

### PR DESCRIPTION
**Pull request by jgravois**
- also moved the 3 samples that were previously shared as blocks into the repo.

i'll fix the merge conflict here _after_ #177 is merged.

### CODE REVIEW

**Comment by jgravois** [comment]
can i get code review and a merge for this one sometime before our next hackerlab on 10/20 _please_?  

i tested all the samples locally and they all run just fine.
(caveat: both geometry engine samples broke at 4.1 so i just left them at 4.0.)

``` js
geometryEngineAsync.geodesicBuffer(stopGeometries, miles, "miles", true).then(function(totalBuffer) {
    // promise never resolves, no error in console.
```

i looked at the [release notes](https://developers.arcgis.com/javascript/latest/guide/release-notes/index.html) from 4.1 and the API reference and didn't find any clues there.

**Comment by andygup** [comment]
@jgravois sure thing. I can give it a review in the a.m.

As for the geometryEngine, maybe put together a jsbin and drop a line to the internal js alias?

**Comment by jgravois** [comment]
bump. (i'd really like to get **_out**_ of the habit of just merging my own work in this repo)

**Comment by jgravois** [comment]
the `geometryEngineAsync` thing is a bug in 4.1.

**Pull request merged**
