### PR TITLE
use panes to control layer order, not callbacks

### LINKED ISSUE #163: Esri-Leaflet lab doesn't render layers in correct order

### PR DESCRIPTION
**Pull request by jgravois**
resolves #163

### CODE REVIEW

**Comment by jgravois** [comment]
can somebody review/merge this **_please**_?

**Comment by alaframboise** [comment]
I didn't test locally but it looks good.

**Comment by jgravois** [comment]
> I didn't test locally but it looks good.

ok.  still waiting on someone to merge then i guess...

**Comment by andygup** [comment]
lemme know if that's bueno. If not I can revert, update, etc

**Pull request merged**
