### PR TITLE
bumped jsapi samples to 3.14

### LINKED ISSUE #41: Update JS API labs to reference 3.14
Currently at 3.13

### PR DESCRIPTION
**Pull request by jgravois**
closes #41

### CODE REVIEW

**Comment by jgravois** [comment]
laid down another commit (which closes #40) as well.

**Comment by nixta** [comment]
Thanks, @jgravois. Let's hold off on merging until after today's lab.

**Comment by jgravois** [comment]
consider this safely stashed until you decide to push the little green button.

**Comment by jgravois** [comment]
^^ @nixta :smile:

**Pull request merged**
