### PR TITLE
Simple (non-ui) geometry engine sample for in-browser operations

### PR DESCRIPTION
**Pull request by nixta**

### CODE REVIEW

**Comment by andygup** [comment]
Looks good, you pushing any more changes or is this ready to merge?

**Comment by alaframboise** [comment]
@nixta can't seem to get the demo to work, no buffers and no errors

**Comment by nixta** [comment]
Click the map, @alaframboise.

**Comment by alaframboise** [comment]
So can we not force the user to know to do that? ;)

**Comment by nixta** [comment]
If they read the instructions, they'll know :)

**Pull request merged**
