### PR TITLE
move all geolocation links to https

### LINKED ISSUE #107: All geolocation samples broken in Chrome
They need to be updated to HTTPS

Reference: https://geonet.esri.com/people/agup-esristaff/blog/2015/05/11/using-a-secure-origin-with-browser-based-geolocation

### PR DESCRIPTION
**Pull request by jgravois**
resolves #107

### CODE REVIEW

**Comment by jgravois** [comment]
can i get code review here when someone has a minute please?
chrome 50 is out now, our session starts in 2 hours, and all of our `geolocation` samples are currently busted. 😸

**Comment by andygup** [comment]
I'll take a quick look

**Comment by andygup** [comment]
Oh wait, this isn't on a branch from a fork? I'm not sure how to view it. Thoughts?

**Comment by andygup** [comment]
Disregard, I'll go about this a different way

**Comment by andygup** [comment]
They all work, just minor issues as identified below. If you don't have time to make the changes, they aren't showstoppers. 

Also, let everyone know they may have to use 127.0.0.1 if working locally.
- locate-query-4.html - initial zoom level after geolocation is too close to the ground.
-  develop/locate_query_leaflet.md - sample apps needs to be moved to this repo from bl.ocks.org.
- develop/locate_turf_leaflet.md - ditto as above
- locate-query-1.html - initial zoom level after geolocation is too close to the ground.
- locate-query-4.html - initial zoom level after geolocation is too close to the ground.

**Comment by jgravois** [comment]
> this isn't on a branch from a fork?

no, i pushed the branch directly upstream.  you can pull down the changes more than one way.

```
git fetch upstream
  > grabs all new activity without merging anything locally
git checkout -b ssl upstream/ssl
  > create a new local branch that tracks the new upstream branch you want to review
```

> initial zoom level after geolocation is too close to the ground.

this is the default behavior of the API widget.  i don't think its worth worrying about here.

> sample apps need to be moved to this repo from bl.ocks.org

be my guest.

**Pull request merged**
