### PR TITLE
new geoenrich address tutorial

### PR DESCRIPTION
**Pull request by jgravois**
live markdown [here](https://github.com/Esri/geodev-hackerlabs/blob/f66152d18b6f6c0b2f6fb0d284d2b9b5c2ff5ad0/develop/enrich_address_search_leaflet.md).  feedback happily accepted (and possibly incorporated) :two_men_holding_hands:

### CODE REVIEW

**Comment by andygup** [comment]
@jgravois I gotta coupl'a comments. Do you want them here or on the branch?

**Comment by alaframboise** [comment]
I know we are jamming right now but it would be cool to follow a similar format to the other .mds. On the other hand, we could always get to later...

**Comment by alaframboise** [comment]
I also noticed the stop symbols are drawing under the lines vs on top in this lab and esri-leaflet add_layers lab.

http://esri.github.io/geodev-hackerlabs/develop/src/add_feature_layers_leaflet.html

**Comment by andygup** [comment]
Yup...for consistency here's a couple quick ones that could be bumped into the sync with the rest:
- The live app should be hosted in the geodev-hackers repo 
- I "think" but I haven't checked that many (most?) of the dev repos refer to jsbin hosting.
- For Step 3 show a code snippet.

**Comment by jgravois** [comment]
> for consistency...
1. as i've [said before](https://github.com/Esri/geodev-hackerlabs/issues/34#issuecomment-140791604), i don't think jsbin is a good tool for teaching web development
2. i don't like including code snippets for people to copy/paste in the tutorials, because they become a crutch.
3. i like [bl.ocks](http://bl.ocks.org/) because they allow people to see the live application and source 
   code on the screen at the same time.

> the stop symbols are drawing under the lines

i'm not sure what's going on with the point symbol draw order.  i'll play around with it.

**Comment by alaframboise** [comment]
Hey @jgravois and @andygup. I merged this so we can get everything done and tested for tomorrow. We can tidy-up later if need be.

**Pull request merged**
